src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Contacts $contact = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getContact(): ?Contacts
    {
        return $this->contact;
    }

    public function setContact(?Contacts $contact): static
    {
        $this->contact = $contact;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue()
    {
        $this->created_at = new \DateTimeImmutable();
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content')
            ->add('contact')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use App\Repository\MessagesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/messages')]
class MessagesController extends AbstractController
{
    #[Route('/', name: 'app_messages_index', methods: ['GET'])]
    public function index(MessagesRepository $messagesRepository): Response
    {
        return $this->render('messages/index.html.twig', [
            'messages' => $messagesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_messages_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $message = new Messages();
        $form = $this->createForm(MessagesType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('app_messages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('messages/new.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_messages_show', methods: ['GET'])]
    public function show(Messages $message): Response
    {
        return $this->render('messages/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_messages_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Messages $message, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MessagesType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_messages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('messages/edit.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_messages_delete', methods: ['POST'])]
    public function delete(Request $request, Messages $message, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $entityManager->remove($message);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_messages_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/messages/_delete_form.html.twig
<form method="post" action="{{ path('app_messages_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/messages/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/messages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Message{% endblock %}

{% block body %}
    {% include 'navbar.html.twig' %}
    <div class="container">
        <h1>Modifier le message</h1>

        <div class="row">
            <div class="col-md-6 offset-md-3">
                {{ form_start(form, {'attr': {'class': 'form'}}) }}

                <div class="form-group">
                    {{ form_label(form.content, 'Contenu') }}
                    {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_label(form.contact, 'Contact') }}
                    {{ form_widget(form.contact, {'attr': {'class': 'form-control'}}) }}
                </div>

                <button type="submit" class="btn btn-primary mt-2">Mettre à jour</button>

                {{ form_end(form) }}
            </div>
        </div>

        <a href="{{ path('app_messages_index') }}" class="btn btn-secondary">Retour à la liste</a>
        {% if is_granted('ROLE_ADMIN') %}
        {{ include('messages/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages index{% endblock %}

{% block body %}
    {% include 'navbar.html.twig' %}
    <div class="container">
        <h1>Messages index</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for message in messages %}
                <tr>
                    <td>{{ message.id }}</td>
                    <td>{{ message.content }}</td>
                    <td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <a href="{{ path('app_messages_show', {'id': message.id}) }}">show</a>
                        <a href="{{ path('app_messages_edit', {'id': message.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_messages_new') }}" class="btn btn-primary">Create new</a>
    </div>
{% endblock %}

templates/messages/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Message{% endblock %}

{% block body %}
    {% include 'navbar.html.twig' %}
    <div class="container">
        <h1>Créer un nouveau message</h1>

        <div class="row">
            <div class="col-md-6 offset-md-3">
                {{ form_start(form, {'attr': {'class': 'form'}}) }}

                <div class="form-group">
                    {{ form_label(form.content, 'Contenu') }}
                    {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_label(form.contact, 'Contact') }}
                    {{ form_widget(form.contact, {'attr': {'class': 'form-control'}}) }}
                </div>

                <button type="submit" class="btn btn-primary">Enregistrer</button>

                {{ form_end(form) }}
            </div>
        </div>

        <a href="{{ path('app_messages_index') }}" class="btn btn-secondary mt-2">Retour à la liste</a>
    </div>
{% endblock %}

templates/messages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages{% endblock %}

{% block body %}
    {% include 'navbar.html.twig' %}
    <div class="container">
        <h1>Messages</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ message.content }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            </tbody>
        </table>

        <a href="{{ path('app_messages_index') }}">back to list</a>

        <a href="{{ path('app_messages_edit', {'id': message.id}) }}">edit</a>

        {% if is_granted('ROLE_ADMIN') %}
        {{ include('messages/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}